# This is a basic workflow to help you get started with Actions

name: AutoRelease

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers the workflow on push or pull request events but only for the release/0.8 branch
  push:
    branches: [ release/0.8 ]
  #pull_request:
  #  branches: [ release/0.7 ]

  
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Using the organization-level secret
  DEPLOYMENT_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Debug
  
jobs:
  build:
    runs-on: windows-latest

    steps:         
    - uses: actions/checkout@v2   
    
    - name: Grab Version
      id: get_version
      shell: powershell
      run: |
        # Read the file content
        $fileContent = Get-Content -Path Razor/Properties/AssemblyInfo.cs
        
        # Filter out comment lines and look for version
        $versionLine = $fileContent | Where-Object { $_ -notmatch '^\s*//' } | Select-String -Pattern 'AssemblyVersion\("([\d\.\w]+)"\)' | Select-Object -First 1
        
        if ($versionLine) {
          $version = $versionLine.Matches.Groups[1].Value
        } else {
          # Try alternative attribute format if first attempt fails
          $versionLine = $fileContent | Where-Object { $_ -notmatch '^\s*//' } | Select-String -Pattern 'AssemblyVersionAttribute\("([\d\.\w]+)"\)' | Select-Object -First 1
          if ($versionLine) {
            $version = $versionLine.Matches.Groups[1].Value
          } else {
            Write-Error "Could not find version information in AssemblyInfo.cs"
            exit 1
          }
        }
        
        Write-Host "Found version: $version"
        echo "version=$version" >> $env:GITHUB_OUTPUT
    
    - name: Show Version
      run: echo "${{steps.get_version.outputs.version}}"
      
    - name: GitHub Tag Exists
      uses: mukunku/tag-exists-action@v1.2.0
      id: checkTag
      with: 
        tag: "v${{steps.get_version.outputs.version}}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        
    - name: Show Tag Existence Result
      run: echo ${{ steps.checkTag.outputs.exists }}
    
    # build   
    - name: Add MSBuild to PATH
      if: ${{ steps.checkTag.outputs.exists }} == false
      uses: microsoft/setup-msbuild@v1 
      
    - name: Display MSBuild version
      run: msbuild -version
      
    - name: Restore NuGet packages
      if: ${{ steps.checkTag.outputs.exists }} == false
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Print expanded MSBuild command
      run: echo msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Build
      if: ${{ steps.checkTag.outputs.exists }} == false
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Zip Razor
      if: ${{ steps.checkTag.outputs.exists }} == false
      id: create_zip
      uses: vimtor/action-zip@v1
      with:
        files: bin/Win32/Debug
        recursive: true
        dest: RazorEnhanced-${{ steps.get_version.outputs.version }}.zip

    # Instead of creating a release in the current repo, checkout the GitHub Pages repo
    - name: Checkout GitHub Pages Repository
      if: ${{ steps.checkTag.outputs.exists }} == false
      uses: actions/checkout@v2
      with:
        repository: RazorEnhanced/razorenhanced.github.io
        path: gh-pages
        token: ${{ secrets.DEPLOYMENT_TOKEN }}

    # Create releases directory if it doesn't exist
    - name: Create releases directory
      if: ${{ steps.checkTag.outputs.exists }} == false
      run: |
        if (!(Test-Path -Path "gh-pages/releases")) {
          New-Item -ItemType Directory -Path "gh-pages/releases"
        }
      shell: pwsh

    # Copy the zip file to the GitHub Pages repo
    - name: Copy release package
      if: ${{ steps.checkTag.outputs.exists }} == false
      run: |
        # Copy versioned zip file
        Copy-Item -Path "RazorEnhanced-${{ steps.get_version.outputs.version }}.zip" -Destination "gh-pages/releases/"
      shell: pwsh

    # Update the latest.json file with version info
    - name: Update latest.json
      if: ${{ steps.checkTag.outputs.exists }} == false
      run: |
        $latestJson = @{
          version = "${{ steps.get_version.outputs.version }}"
          zipUrl = "https://razorenhanced.github.io/releases/RazorEnhanced-${{ steps.get_version.outputs.version }}.zip"
          releaseDate = (Get-Date -Format "yyyy-MM-dd")
        } | ConvertTo-Json

        Set-Content -Path "gh-pages/releases/latest.json" -Value $latestJson -Force
      shell: pwsh

    # Commit and push changes to the GitHub Pages repo
    - name: Commit and push changes
      if: ${{ steps.checkTag.outputs.exists }} == false
      run: |
        cd gh-pages
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add releases/
        git commit -m "Add release version ${{ steps.get_version.outputs.version }}"
        git push
      shell: pwsh

# Create a tag using PowerShell and GitHub API
    - name: Create Tag
      if: ${{ steps.checkTag.outputs.exists }} == false
      run: |
        # Set git identity for local operations
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
        # Get current commit SHA
        $commitSha = $(git rev-parse HEAD)
        Write-Host "Creating tag for commit: $commitSha"
        
        # Create API request body
        $body = @{
          ref = "refs/tags/v${{ steps.get_version.outputs.version }}"
          sha = $commitSha
        } | ConvertTo-Json
        
        # Send API request to create tag
        $headers = @{
          Authorization = "token ${{ secrets.DEPLOYMENT_TOKEN }}"
          Accept = "application/vnd.github.v3+json"
        }
        
        try {
          $response = Invoke-RestMethod -Uri "https://api.github.com/repos/RazorEnhanced/RazorEnhanced/git/refs" -Method Post -Headers $headers -Body $body -ContentType "application/json"
          Write-Host "Tag created successfully: $($response.ref)"
        } catch {
          Write-Error "Failed to create tag: $_"
          Write-Error $_.Exception.Response.StatusCode
          Write-Error $_.Exception.Response.StatusDescription
          Write-Error $_.Exception.Response.Content
          exit 1
        }
      shell: pwsh
      
# Clean up old releases to save space
    - name: Clean up old releases
      if: ${{ steps.checkTag.outputs.exists }} == false
      run: |
        # Navigate to releases directory
        cd gh-pages/releases
        
        # Get all version zip files sorted by last modified date (newest first)
        $allZips = Get-ChildItem -Filter "RazorEnhanced-*.zip" | 
                   Sort-Object -Property LastWriteTime -Descending
        
        # Keep only the latest 50 versions
        if ($allZips.Count -gt 50) {
          Write-Host "Found $($allZips.Count) releases, keeping the 50 most recent ones"
          foreach ($zip in $allZips[50..($allZips.Count-1)]) {
            Write-Host "Removing old release: $($zip.Name)"
            Remove-Item $zip.FullName -Force
          }
        } else {
          Write-Host "Found $($allZips.Count) releases, all will be kept"
        }
      shell: pwsh
